[package]
name = "terminus_types"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
blake3 = "1.0.0"
serde = { version = "1.0.126", features = ["derive"] }
